version: "3.1"

services:
  firstTask:
    image: firstTask:1.0
    env_file:
      - .env
    ports:
      - "2000:2000"
      - "3000:3000"
      - "2443:2443"
      - "3443:3443"
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: userFresDB
      MONGO_INITDB_ROOT_PASSWORD: passFresDB
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db:rw"
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: userFresDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: passFresDB
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8085:8081"
